# Generated by Django 5.2.5 on 2025-09-01 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('gold_price_21', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold_price_24', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('Cash', 'Cash'), ('Visa', 'Visa')], default='Cash', max_length=255)),
                ('invoice_type', models.CharField(choices=[('Sale', 'Sale'), ('Return Packing', 'Return Packing'), ('Return Unpacking', 'Return Unpacking')], max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_invoices', to='core.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_invoices', to='core.customer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_invoices', to='core.seller')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_invoices', to='core.warehouse')),
            ],
            options={
                'db_table': 'gold_invoice',
            },
        ),
        migrations.CreateModel(
            name='GoldInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_carat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_stamp_enduser', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_quantity', models.BigIntegerField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor_name', models.CharField(max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.goldinvoice')),
            ],
            options={
                'db_table': 'gold_invoice_items',
            },
        ),
        migrations.CreateModel(
            name='SilverInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('silver_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('Cash', 'Cash'), ('Visa', 'Visa')], default='Cash', max_length=255)),
                ('invoice_type', models.CharField(choices=[('Sale', 'Sale'), ('Return Packing', 'Return Packing'), ('Return Unpacking', 'Return Unpacking')], max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silver_invoices', to='core.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silver_invoices', to='core.customer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silver_invoices', to='core.seller')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silver_invoices', to='core.warehouse')),
            ],
            options={
                'db_table': 'silver_invoice',
            },
        ),
        migrations.CreateModel(
            name='SilverInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_carat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_stamp_enduser', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_quantity', models.BigIntegerField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor_name', models.CharField(max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.silverinvoice')),
            ],
            options={
                'db_table': 'silver_invoice_items',
            },
        ),
    ]
